module.exports = {
  ACCOUNT_CREATED: 'account.created',
  ACCOUNT_UPDATED: 'account.updated',
  ACCOUNT_DEACTIVATED: 'account.deactivated',
  CONTACT_UPDATED: 'contact.updated',
  METER_ADDED: 'meter.added',
  METER_DEACTIVATED: 'meter.deactivated',
  READING_SUBMITTED: 'meter.reading.submitted',
  READING_ROLLOVER: 'meter.reading.rollover',
  READING_RESET: 'meter.reading.reset',
  ASSESSMENT_CREATED: 'assessment.created',
  ASSESSMENT_REVIEWED: 'assessment.reviewed',
  ASSESSMENT_OVERRIDDEN: 'assessment.overridden',
  BILLING_DAILY_COMPLETED: 'billing.daily.completed',
  RATE_CREATED: 'rate.created',
  RATE_UPDATED: 'rate.updated',
  USER_LOGIN: 'user.login',
  USER_ACCESS_DENIED: 'user.access.denied',
};
