<#
.SYNOPSIS
    Applies sanitization replacements from an M365 Copilot audit Excel file.

.DESCRIPTION
    Reads an Excel spreadsheet generated by M365 Copilot's PII audit,
    then applies find-and-replace operations across the source files.

    Expected Excel columns:
    A: FileName
    B: LineNumber
    C: FoundValue (the sensitive data to replace)
    D: DataType
    E: RiskLevel
    F: SuggestedReplacement (what to replace it with)
    G: Context

.PARAMETER AuditFile
    Path to the Excel audit file (.xlsx)

.PARAMETER SourceDir
    Path to the source code directory to sanitize

.PARAMETER DryRun
    Preview changes without modifying files

.PARAMETER BackupFirst
    Create a backup of the source directory before applying changes

.PARAMETER SkipLow
    Skip LOW risk items (only apply HIGH and MEDIUM)

.EXAMPLE
    .\Apply-Sanitization.ps1 -AuditFile "FRS_Audit.xlsx" -SourceDir "C:\FRS" -DryRun
    .\Apply-Sanitization.ps1 -AuditFile "FRS_Audit.xlsx" -SourceDir "C:\FRS" -BackupFirst
#>

param(
    [Parameter(Mandatory=$true)]
    [string]$AuditFile,

    [Parameter(Mandatory=$true)]
    [string]$SourceDir,

    [switch]$DryRun,
    [switch]$BackupFirst,
    [switch]$SkipLow
)

# --- Validate inputs ---
if (-not (Test-Path $AuditFile)) {
    Write-Error "Audit file not found: $AuditFile"
    exit 1
}

if (-not (Test-Path $SourceDir)) {
    Write-Error "Source directory not found: $SourceDir"
    exit 1
}

$AuditFile = Resolve-Path $AuditFile
$SourceDir = Resolve-Path $SourceDir

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "  SAWS Code Sanitization Tool" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Audit file : $AuditFile"
Write-Host "Source dir  : $SourceDir"
Write-Host "Mode       : $(if ($DryRun) { 'DRY RUN (preview only)' } else { 'APPLY CHANGES' })"
Write-Host ""

# --- Backup if requested ---
if ($BackupFirst -and -not $DryRun) {
    $backupDir = "$SourceDir`_backup_$(Get-Date -Format 'yyyyMMdd_HHmmss')"
    Write-Host "Creating backup at: $backupDir" -ForegroundColor Yellow
    Copy-Item -Path $SourceDir -Destination $backupDir -Recurse
    Write-Host "Backup complete." -ForegroundColor Green
    Write-Host ""
}

# --- Read Excel file ---
Write-Host "Reading audit file..." -ForegroundColor Yellow

try {
    $excel = New-Object -ComObject Excel.Application
    $excel.Visible = $false
    $excel.DisplayAlerts = $false
    $workbook = $excel.Workbooks.Open($AuditFile)
    $sheet = $workbook.Sheets.Item(1)

    $replacements = @()
    $row = 2  # Skip header row

    while ($sheet.Cells.Item($row, 1).Value2 -ne $null) {
        $entry = [PSCustomObject]@{
            FileName     = $sheet.Cells.Item($row, 1).Value2
            LineNumber   = $sheet.Cells.Item($row, 2).Value2
            FoundValue   = $sheet.Cells.Item($row, 3).Value2
            DataType     = $sheet.Cells.Item($row, 4).Value2
            RiskLevel    = $sheet.Cells.Item($row, 5).Value2
            Replacement  = $sheet.Cells.Item($row, 6).Value2
            Context      = $sheet.Cells.Item($row, 7).Value2
        }

        if ($SkipLow -and $entry.RiskLevel -eq 'LOW') {
            $row++
            continue
        }

        if ($entry.FoundValue -and $entry.Replacement) {
            $replacements += $entry
        }
        $row++
    }

    $workbook.Close($false)
    $excel.Quit()
    [System.Runtime.Interopservices.Marshal]::ReleaseComObject($excel) | Out-Null

} catch {
    Write-Error "Failed to read Excel file: $_"
    Write-Host ""
    Write-Host "If Excel COM is not available, you can export to CSV and use the CSV version." -ForegroundColor Yellow

    # Fallback: try CSV
    if ($AuditFile -like "*.csv") {
        $csvData = Import-Csv $AuditFile
        $replacements = $csvData | ForEach-Object {
            [PSCustomObject]@{
                FileName    = $_.FileName
                LineNumber  = $_.LineNumber
                FoundValue  = $_.FoundValue
                DataType    = $_.DataType
                RiskLevel   = $_.RiskLevel
                Replacement = $_.SuggestedReplacement
                Context     = $_.Context
            }
        }
        if ($SkipLow) {
            $replacements = $replacements | Where-Object { $_.RiskLevel -ne 'LOW' }
        }
        $replacements = $replacements | Where-Object { $_.FoundValue -and $_.Replacement }
    } else {
        exit 1
    }
}

Write-Host "Found $($replacements.Count) replacements to apply." -ForegroundColor Green
Write-Host ""

# --- Group by risk level ---
$highCount = ($replacements | Where-Object { $_.RiskLevel -eq 'HIGH' }).Count
$medCount = ($replacements | Where-Object { $_.RiskLevel -eq 'MEDIUM' }).Count
$lowCount = ($replacements | Where-Object { $_.RiskLevel -eq 'LOW' }).Count

Write-Host "  HIGH risk  : $highCount" -ForegroundColor Red
Write-Host "  MEDIUM risk: $medCount" -ForegroundColor Yellow
Write-Host "  LOW risk   : $lowCount" -ForegroundColor Gray
Write-Host ""

# --- Preview / Apply ---
$filesModified = @{}
$totalReplacements = 0
$errors = @()

# Group replacements by file for efficiency
$byFile = $replacements | Group-Object -Property FileName

foreach ($fileGroup in $byFile) {
    $fileName = $fileGroup.Name
    $filePath = Join-Path $SourceDir $fileName

    # Try to find the file (may be in a subdirectory)
    if (-not (Test-Path $filePath)) {
        $found = Get-ChildItem -Path $SourceDir -Recurse -Filter $fileName -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($found) {
            $filePath = $found.FullName
        } else {
            $errors += "File not found: $fileName"
            Write-Host "  SKIP: $fileName (not found)" -ForegroundColor Red
            continue
        }
    }

    $content = Get-Content $filePath -Raw -ErrorAction SilentlyContinue
    if (-not $content) {
        $errors += "Could not read: $fileName"
        continue
    }

    $originalContent = $content
    $fileReplacementCount = 0

    foreach ($entry in $fileGroup.Group) {
        $found = $entry.FoundValue.ToString().Trim()
        $replacement = $entry.Replacement.ToString().Trim()

        if ($content.Contains($found)) {
            if ($DryRun) {
                Write-Host "  WOULD REPLACE in $($fileName):" -ForegroundColor Cyan
                Write-Host "    [$($entry.RiskLevel)] $($entry.DataType)" -ForegroundColor $(
                    switch ($entry.RiskLevel) { 'HIGH' { 'Red' } 'MEDIUM' { 'Yellow' } default { 'Gray' } }
                )
                Write-Host "    FROM: $found" -ForegroundColor Red
                Write-Host "    TO  : $replacement" -ForegroundColor Green
                Write-Host ""
            }

            $content = $content.Replace($found, $replacement)
            $fileReplacementCount++
            $totalReplacements++
        } else {
            # Value might have been already replaced or slightly different
            Write-Host "  NOTE: Value not found in $($fileName): '$found'" -ForegroundColor DarkGray
        }
    }

    if (-not $DryRun -and $content -ne $originalContent) {
        Set-Content -Path $filePath -Value $content -NoNewline
        $filesModified[$fileName] = $fileReplacementCount
        Write-Host "  MODIFIED: $fileName ($fileReplacementCount replacements)" -ForegroundColor Green
    } elseif ($DryRun -and $fileReplacementCount -gt 0) {
        $filesModified[$fileName] = $fileReplacementCount
    }
}

# --- Summary ---
Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "  Summary" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Total replacements: $totalReplacements"
Write-Host "Files modified    : $($filesModified.Count)"
Write-Host ""

if ($errors.Count -gt 0) {
    Write-Host "Errors:" -ForegroundColor Red
    $errors | ForEach-Object { Write-Host "  - $_" -ForegroundColor Red }
    Write-Host ""
}

if ($DryRun) {
    Write-Host "This was a DRY RUN. No files were modified." -ForegroundColor Yellow
    Write-Host "Run again without -DryRun to apply changes." -ForegroundColor Yellow
} else {
    Write-Host "Sanitization complete." -ForegroundColor Green
    if ($BackupFirst) {
        Write-Host "Original files backed up at: $backupDir" -ForegroundColor Gray
    }
}

# --- Generate report ---
$reportPath = Join-Path (Split-Path $AuditFile) "SANITIZATION_REPORT_$(Get-Date -Format 'yyyyMMdd_HHmmss').md"

$report = @"
# Sanitization Report

**Date:** $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
**Audit File:** $(Split-Path $AuditFile -Leaf)
**Source Directory:** $SourceDir
**Mode:** $(if ($DryRun) { 'DRY RUN' } else { 'APPLIED' })

## Summary

| Metric | Count |
|--------|-------|
| Total findings in audit | $($replacements.Count) |
| Replacements applied | $totalReplacements |
| Files modified | $($filesModified.Count) |
| Errors | $($errors.Count) |

## Risk Breakdown

| Risk Level | Count |
|-----------|-------|
| HIGH | $highCount |
| MEDIUM | $medCount |
| LOW | $lowCount |

## Files Modified

| File | Replacements |
|------|-------------|
$(($filesModified.GetEnumerator() | ForEach-Object { "| $($_.Key) | $($_.Value) |" }) -join "`n")

$(if ($errors.Count -gt 0) {
"## Errors`n`n" + ($errors | ForEach-Object { "- $_" }) -join "`n"
})

## Next Steps

1. Review modified files to ensure code logic is intact
2. Run the M365 Copilot verification prompt to confirm all PII is removed
3. Test the sanitized code compiles/runs correctly
4. Share the sanitized code with AI migration tools
"@

Set-Content -Path $reportPath -Value $report
Write-Host ""
Write-Host "Report saved to: $reportPath" -ForegroundColor Cyan
